server:
    servlet:
        context-path: /app
        port: 8080

logging:
    config: classpath:log4j2.xml

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/birdchain?allowPublicKeyRetrieval=true&useSSL=false&useUniCode=yes&characterEncoding=utf8&serverTimezone=Asia/Seoul
        username: root
        password: 1234

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
cloud:
    aws:
        s3:
            bucket: birdchain
        stack.auto: false
        region.static: ap-northeast-2
        credentials:
            accessKey: AKIAWDNHI63CVUB44IDA
            secretKey: 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

