server:
  servlet:
    context-path: /api
    port: 8080

logging:
  config: classpath:log4j2.xml

spring:
  profiles:
    include: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/birdchain?allowPublicKeyRetrieval=true&useSSL=false&useUniCode=yes&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: "!@104birdchain"
    
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: ${hibernate.ddl-auto}
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나 당 최대 사이즈
      max-request-size: 20MB # 요청 당 최대 사이즈

cloud:
  aws:
    s3:
      bucket: birdchain
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAWDNHI63CVUB44IDA
      secretKey: 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


cors:
  allowedOrigins: http://localhost:3000, http://k8b104.p.ssafy.io:3000, https://k8b104.p.ssafy.io
